### ISSUE TITLE
faulthandler does not trap segv in background threads on Windows

### ISSUE THREAD

**Issue by davidfraser** [haypo/faulthandler#13]
I've installed faulthandler 2.4 from pip on a Python 2.7 installation in Windows 2003.

Faulthandler only catches segfaults in the thread in which enable was called. If a crash occurs in a different thread, it is not caught.

Testing with the following program:

``` python
import faulthandler
import sys
import time
import threading

ENABLE_IN_MAIN = True
ENABLE_IN_THREAD = False

t = threading.current_thread

def test_crash():
    print ('Starting test in %r' % t())
    if ENABLE_IN_THREAD:
        print ('Enabling faulthandler in %r' % t())
        faulthandler.enable()
    time.sleep(0.1)
    print ('Crashing in %r' % t())
    faulthandler._sigsegv()

if ENABLE_IN_MAIN:
    print ('Enabling faulthandler in %r' % t())
    faulthandler.enable()

print ('Launching BackgroundThread')
threading.Thread(target=test_crash, name="BackgroundThread").start()
time.sleep(1)
print('Survived in %r' % t())
```

Setting `ENABLE_IN_MAIN` to `False` and `ENABLE_IN_THREAD` to `True` causes the segfault to be caught (but then segfaults in the main thread are not caught). (On Linux, tests in either thread are caught successfully)

It would be helpful to have tests for crashes in other threads in the test suite too...

**Comment by haypo** [comment]
Hi,

I just wrote a new implementation of faulthandler on Windows, see:
https://bugs.python.org/issue23848

The patch is not merged yet, but I expect that faulthandler will work in more cases with the exception handler API.

Victor

**Comment by davidfraser** [comment]
That sounds perfect, looking forward to it!

**Comment by haypo** [comment]
I don't plan to backport the feature in this backport, so I close the issue. Use Python 3.6 on Windows ;-)

**Comment by nirgilboa** [comment]
FYi faulthander 3.0 now includes a backport for the Windows handler from CPython 3.5+
