### ISSUE TITLE
Support PYTHONFAULTHANDLER env var

### ISSUE THREAD

**Issue by ionelmc** [haypo/faulthandler#14]
Would you be interested in having support for that? If yes, I can make a PR for that (some `.pth` trickery a la https://pypi.python.org/pypi/hunter).

**Comment by haypo** [comment]
I hate .pth hacks. Personally, when I need faulthandler, I was always able to modify the source code.

Python 3.3+ accepts -X faulthandler command line option and PYTHONFAULTHANDLER environment variables.

Can you show me some code to evaluate of ugly it is? :)

**Comment by ionelmc** [comment]
It's fairly simple:
https://github.com/ionelmc/python-hunter/blob/master/setup.py

On Friday, April 17, 2015, Victor Stinner <notifications@github.com> wrote:

> I hate .pth hacks. Personally, when I need faulthandler, I was always able
> to modify the source code.
>
> Python 3.3+ accepts -X faulthandler command line option and
> PYTHONFAULTHANDLER environment variables.
>
> Can you show me some code to evaluate of ugly it is? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haypo/faulthandler/issues/14#issuecomment-93849286>.
>


-- 

Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by haypo** [comment]
Oh, I found the pth:
https://github.com/ionelmc/python-hunter/blob/master/src/hunter.embed

So ok, it's quite simple in fact :-) Ok for such feature, please send a pull request (or a patch).

In CPython, faulthandler.enable() is called if PYTHONFAULTHANDLER environment variable is defined *and* not empty.

**Comment by ionelmc** [comment]
@haypo do you still want to have distutils-only setup.py ?

**Comment by haypo** [comment]
Setuptools is mainstream :-) Ok to drop distutils support.
