### ISSUE TITLE
PyPy support

### ISSUE THREAD

**Issue by thedrow** [haypo/faulthandler#17]
Is it possible to make this library work with PyPy?
How? Do we need to write CFFI bindings?

**Comment by haypo** [comment]
Hi,

faulthandler is very specific to the CPython internals, see:
https://github.com/haypo/faulthandler/blob/master/faulthandler.c#L238

It would be nice to support PyPy, but IMHO it must be a separated project. I don't know PyPy internals, I don't know it would be possible to implement faulthandler in PyPy, especially with the JIT.

Victor

**Comment by jayvdb** [comment]
Just noting that while PyPy now has a faulthandler module, it is not functional : https://bitbucket.org/pypy/pypy/issues/2294/faulthandler-not-really-implemented

**Comment by eric-wieser** [comment]
@jayvdb: Looks to be fixed now, based on the status of that issue.

**Comment by jayvdb** [comment]
Documented a while ago by @vstinner as being builtin since PyPy 5 (https://github.com/vstinner/faulthandler/commit/43423a2ab18)
