### ISSUE TITLE
readthedocs

### ISSUE THREAD

**Issue by jayvdb** [haypo/faulthandler#21]
The link http://faulthandler.readthedocs.org is used everywhere (pypi, github, etc), but it is now 404, and appears to have been that was since October 2015, or soon after.

https://web.archive.org/web/20151013162218/http://faulthandler.readthedocs.org/en/latest/

**Comment by haypo** [comment]
I got a notice about migration from readthedocs.org to readthedocs.io, but I didn't know that I had to regenerate the doc :-/ I forced a build, it fixed the issue.

I also update the URL to the doc. Thanks for the bug report!
