### ISSUE TITLE
faulthandler_suppress_crash_report could be a python function

### ISSUE THREAD

**Issue by tarcisiofischer** [haypo/faulthandler#22]
I see that many functions are calling the faulthandler_suppress_crash_report, but this function cannot be explicitly called from python.

What do you think about exposing it as a python function?

**Comment by haypo** [comment]
I dislike exposing such low level function.

Anyway, this project is a backport for Python 2.7. I suggest you to propose the idea in CPython bug tracker: http://bugs.python.org/ new features occur there. I only make minimum work to maintain this backport.
